package greetings

import (
	"errors"
	"fmt"
)

// GO can return multiple values
func Hello(name string) (string, error) {
	//Error instance is generated by imported function
	if name == "" {
		return "", errors.New("empty name")
	}

	//Use fmt imported function to generate name
	//Need := to declare and assign at same time
	message := fmt.Sprintf("Hi, %v. Welcome!", name)

	return message, nil
}
